### ISSUE TITLE
Soldiers much stronger in own territory?

### ISSUE THREAD

**Issue by Karol-G** [paulwedeck/settlers-remake#11]
Hi,

first of all thanks for the active fork. That is really amazing!
One thing I noticed is that soldiers are much stronger in their respective territory than outside. This makes it very difficult to actually win the game. Is that a bug or intended? If it is intended then it would be cool if there could be an option to disable it (in-game or through a config file). For a casual player like me it is very difficult to make gains wit the current behaviour.

Game version: v0.5.3-alpha

Best,
Karol

**Comment by paulwedeck** [comment]
Hello,
the combat strength mechanic should be the same as in the original game.
Maybe read [this](https://wiki.siedler3.net/doku.php?id=alobby:tipps:das_gold_und_die_kampfkraft) and https://github.com/jsettlers/settlers-remake/issues/162 for reference.

**Comment by Karol-G** [comment]
Hmmm, I did not remeber it like that, but maybe I am wrong. Plus, the guys in the thread know probably more than me. Thanks for the answer though.
