### ISSUE TITLE
Cannot change number of players (or other settings) in multiplayer

### ISSUE THREAD

**Issue by Karol-G** [paulwedeck/settlers-remake#12]
Hi,

in multiplayer it is not possible to change any settings such as number of players or starting resources.
In singleplayer this can be changed.

Game version: v0.5.3-alpha

Best,
Karol

**Comment by Karol-G** [comment]
It would be really cool if the player count could be changed. Especially on maps with 16 players. Would this be an easy fix or is this complicated to do in multiplayer?

**Comment by paulwedeck** [comment]
I am quite busy atm but I will look into this in the next days.

**Comment by Karol-G** [comment]
Thanks a lot and no worries!

**Comment by Karol-G** [comment]
Thanks a lot!
