### ISSUE TITLE
Cancel an attack and withdraw doesn't work

### ISSUE THREAD

**Issue by Speciesx** [paulwedeck/settlers-remake#23]
Once the soldiers start an attack or get attacked, it's impossible to withdraw.

**Comment by Karol-G** [comment]
You have to press control and then give an order. That order then has highest priority.

**Comment by HiranChaudhuri** [comment]
I could not remember such behaviour in the original game. But the more I play the more I understand this is a really good feature - you need 'normal' and 'high' priority commands. To inexperienced players it is not obvious pressing Ctrl would have any effect, so we might want to think of hints in the game. Some documentation (who would read that?), or tutorial games.

**Comment by paulwedeck** [comment]
From what I can see the force move function actually works fine. Feel free to open a new issue if the function no longer works.
