### ISSUE TITLE
[Shadow bug] Entire GUI and most objects disapear

### ISSUE THREAD

**Issue by Karol-G** [paulwedeck/settlers-remake#26]
Hi,

there is this very frequent bug that lets the entire GUI and most objects (buildings, settlers, etc.) disapear for a certain area.
This often happens when the fog of war is lifted and then re-emerges in some area that is occupied by the enemy.

 How to reproduce:
Play for 10-20 minutes and then send your soldiers or pioniers through the enemy territory. There is a high chance that the bug will occur.

This is currently the most annoying bug I belive as it happens in every game and makes playing very hard. As long as the buggy area is visible at the screen the entire GUI and most objects disapear. The only way to avoid it is to move the camera away from that region or zoom in to ant-level, so that everything reappears.

Here is an example of how it looks with the bug and how it should actually look:
![001](https://user-images.githubusercontent.com/3471895/152643456-ab117670-a3c5-4930-8c55-c8835b9c9fec.PNG)
![002](https://user-images.githubusercontent.com/3471895/152643460-84c68d2b-528c-4b70-9d2d-5cee18c92ac3.PNG)

Best,
Karol

**Comment by paulwedeck** [comment]
Hello,
please send me a _replay.log and _out.log file for one of these games.
You can find them under logs in a separate folder.
If the map is not a default map or if this is a loaded savegame I need the map/savegame as well.

**Comment by Karol-G** [comment]
Here are both files:
[Shadow Bug.zip](https://github.com/paulwedeck/settlers-remake/files/8008091/Shadow.Bug.zip)

The map is default map and named something with "Teamwork".

**Comment by paulwedeck** [comment]
Which version of jsettlers are you using?

**Comment by Karol-G** [comment]
The version is from this commit: 73057f5bc0a7b5d8b81e6c5550b2b51ff64821bf

**Comment by Karol-G** [comment]
The build v0.5.3-alpha3 from this commit 3502df7a660e3809e337d558c8f07158dc2fca9e

**Comment by paulwedeck** [comment]
Well, I can't reproduce the bug.
Have you checked your java version? Any version before java 11 will no longer work.
Also 3502df7 is not v0.5.3-alpha3 but v0.5.3-alpha.

If its not the java version please download the most recent version https://github.com/paulwedeck/settlers-remake/releases/tag/v0.5.3-alpha3 and try to trigger it on the map 400-2-Close or 6 players fun (these are builtin jsettlers maps) and send me the new _replay.log and _out.log files.

**Comment by Karol-G** [comment]
Sorry, I meant v0.5.3-alpha.

I downloaded the newest v0.5.3-alpha3, installed openjdk 17 and was able to reproduce the bug on the map 400-2-Close.

Here are the files:
[Shadow Bug.zip](https://github.com/paulwedeck/settlers-remake/files/8008201/Shadow.Bug.zip)

If you want to reproduce ist fast:
Start a game, set the game speed up to 50, wait 10 minutes of ingame time, make 50-100 pioniers and walk through the enemy territory for 2 minutes. Chances are high that it will happen.

**Comment by Karol-G** [comment]
I tested the new version and was unable to reproduce the bug. So it seems to be fixed. Thanks a lot!
