### ISSUE TITLE
Messages unrelated to map positions

### ISSUE THREAD

**Issue by HiranChaudhuri** [paulwedeck/settlers-remake#28]
When I see a message such as 'Woodcutter cannot find any trees in it's working area' it just appears on the screen, and I have to search for which woodcutter this might refer to.
I remember the original game would actually center on the location where something happened.

Is it possible to be added to the remake as well?

**Comment by HiranChaudhuri** [comment]
Looking at the code, it seems messages do have a map position attached:

https://github.com/paulwedeck/settlers-remake/blob/master/jsettlers.common/src/main/java/jsettlers/common/menu/messages/IMessage.java#L72

So it is more about the user presentation.

**Comment by paulwedeck** [comment]
Admittedly I have never actually used this feature before but you can show the location of one of the messages by pressing the space bar.

**Comment by HiranChaudhuri** [comment]
Hmmm. Unlike the original game, that is. The buttons to the bottom left are unused but the new behaviour is quite good. :-)
