### ISSUE TITLE
Load multiplayer game?

### ISSUE THREAD

**Issue by Karol-G** [paulwedeck/settlers-remake#30]
Hi,

I played a match with a friend yesterday and my internet broke down. He saved the game, but we could not find an option to host the saved multiplayer game and continue to play. I assume there is currently no way to do this? Is this feature on the "roadmap"?

Best,
Karol

**Comment by paulwedeck** [comment]
Yes there is currently no way of continuing/(re)hosting a save game as a multiplayer game.
I am currently working on finishing the last few missing gameplay features (the buildings of the Amazons and siege engines) and then I will look into all the stuff related to networking and the main menu(s) but it will probably take some time until I know the code enough to implement loading of multiplayer save games.

**Comment by Karol-G** [comment]
Sounds great! looking forward to it :)

Best,
Karol

**Comment by Karol-G** [comment]
Hey @paulwedeck,

I assume loading a multiplayer savegame is still not possible, right?

Best,
Karol

**Comment by paulwedeck** [comment]
Hi Karol,
there is currently no development ongoing.
Regards
Paul
