### ISSUE TITLE
font to small in maximized window

### ISSUE THREAD

**Issue by Speciesx** [paulwedeck/settlers-remake#37]
<img width="1921" alt="javaw_2022_03_28_13_29_29_752" src="https://user-images.githubusercontent.com/1196375/160390972-25875842-ed29-46c3-9a63-90540e3a3106.png">
<img width="1921" alt="javaw_2022_03_28_13_28_34_453" src="https://user-images.githubusercontent.com/1196375/160390962-7cef6ecc-de86-4770-ac05-44703105cf89.png">

**Comment by paulwedeck** [comment]
There is a scale slider under settings

**Comment by Speciesx** [comment]
GUI scale set to 200%.

Ingame font are ok now, except for the tiny soldier icon
<img width="1920" alt="1" src="https://user-images.githubusercontent.com/1196375/160391884-8ec77dcd-4310-43f5-a13f-4a24aa5a0237.PNG">

but main menu is messed up.
<img width="1920" alt="2" src="https://user-images.githubusercontent.com/1196375/160391952-5f7cf67f-6ce7-4d69-a05e-53f61ff32aff.PNG">
