### ISSUE TITLE
Wrong images in the settler statistic panel

### ISSUE THREAD

**Issue by nptr** [paulwedeck/settlers-remake#5]
Hello,

In the statistic panel for the romans the images seem to be off. See the attached screenshot. For the amazons is fine.
I identified this commit: 887d2361b23c2993282a2e582927f3b251c452c5
The image references in `StatisticLayoutRomans.xml` seem to have been generalized with `<mappedImage>` which seems to have its values from `linkmap.txt`

Now the values I see in the linkmap are different from what I'd expect. I'd need `original_14_GUI_192 `for the geologist but the file contains `original_14_GUI_186` for example. I have my resources from the S3 Demo.

Is this a bug or intentional? (no demo support anymore?)

![StatPanelRomans](https://user-images.githubusercontent.com/5485569/121817847-209f6b00-cc84-11eb-84bb-9a6c339820e7.png)

**Comment by paulwedeck** [comment]
Hello,
yes this was a bug and I will continue supporting the S3 demo version but sadly they don't contain all images. Especially Egyptians and Asians are missing but also Ships.

"original_14_GUI_186" is the correct image because this is the image id in the Gold Edition of S3.

To fix this bug you can either manually edit the corresponding files in your jar file or you can change the `settlers-folder-version-id` in your .jsettlers in `%APPDATA%\\.jsettlers\\` to the old version id of your demo version (e.g. to `87473709065811243` if you have the multiplayer demo or` -1282419180527137435` if you have the amazon demo).

**Comment by nptr** [comment]
I checked out your latest changes and compiled again. I also removed the .jsettler file.

When I start the game and newly select the resources, it uses this version-id: `-7625624354234896191` (Gold Edition?)
That doesn't work however. When I change it to `-139181943176809049` (Amazon Demo) it works.

I was under the impression there is a detection system in place or am I wrong? If there is, you can also give me some hints on where to start and I'll investigate myself why it fails me.

**Comment by paulwedeck** [comment]
My version of the Gold Edition gets the version id 3599955930233092572.
This "version id" actually is just a hash over some (all?) images in the gfx files.
The reason why the hash was wrong is that the format of the image data was changed from 5-5-5-1 to 4-4-4-4 but the generator for the mapping of gold edition image links to image links in non gold edition gfx directories wasn't rerun.

If you own the gold edition you can try generating a mapping for your demo version with `jsettlers.graphics.debug.DatFileMappingComparator`.

I downloaded the amazon demo from the link in the readme to generate this new mapping and as you can see only the hash and none of the images changed.

> If there is, you can also give me some hints on where to start and I'll investigate myself why it fails me.

You probably want `DatFileUtils#generateOriginalVersionId`.

**Comment by nptr** [comment]
I am using the amazon demo from the readme as well. I also downloaded it again just to make sure. Still not getting `-139181943176809049`. Unfortunately I don't own a gold version so I can't say what id/hash I have there.

But I guess we can figure it out based on the demo version as well.
Since there are a lot of things involved in the hashing algorithm, I'd like to check some basics first:

Invoking `DatFileUtils#generateOriginalVersionId` with just `Siedler3_01.f8007e01f.dat` gets me a list of 140 hashes starting with those 5 elements:
```
-1362539726118059196
-3540076462626835916
5690429081540103628
4809428464090157057
6099505894538120134
````

Invoking it with the full gfx folder, I end up with 2198 hashes before they are merged with `Long.toString(hashes.hash())`.
Can you reproduce it so far on your end?

**Comment by paulwedeck** [comment]
Yes, these numbers are all of the same for me. I also tried this with java 8, 11 and 16.

**Comment by nptr** [comment]
Hmm. Assuming the rest of the hashes also match, there must an unexpected dependency in this algorithm.
But based on 5 hashes I can't even confidently conclude that.

I am on Java 8 Update 144 btw, but that doesn't seem to matter much.

**Comment by paulwedeck** [comment]
Maybe the gui hashes are wrong.
I added a breakpoint in DatFileUtils in line 37 inside of the lambda (the variable should be reader)
The first file is 01 and the second 03.

03 has 441 gui files with  -4242133963573718799 being the first one and the last one is 1884655196440010721.

**Comment by nptr** [comment]
Excuse my late response, I am quite busy atm...
I get the same numbers :( But I exported all hashes now from DatFileUtils.java, using the "Hashes" object from line 34.

```
		Writer writer = new BufferedWriter(new OutputStreamWriter(
				new FileOutputStream("D:\\all.txt", true), "UTF-8"));

		for(long h : hashes.getHashes())
		{
			writer.append(Long.toString(h));
			writer.append("\r\n");
		}
		writer.close();
```

You could do the same and then diff in a text editor. 

Hashes: [all.txt](https://github.com/paulwedeck/settlers-remake/files/6689567/all.txt)

**Comment by paulwedeck** [comment]
I think I found something.
https://docs.oracle.com/javase/8/docs/api/java/io/File.html#compareTo-java.io.File-

>  The ordering defined by this method depends upon the underlying system

If I sort like its done on windows I get -7625624354234896191 too for the amazon demo.

**Comment by nptr** [comment]
Nice, that must be it then. Will you make the fix?

**Comment by nptr** [comment]
Works, thanks!
