### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by matusfaro** [paulwedeck/settlers-remake#74]
Android (SM-S918W) with JSettlers version: v0.6.0.6-alpha.

```
07-02 22:54:54.088 11398 11398 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 728024 free bytes and 710KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
```

I played "Craters" map and let the computer build a LOT of things. I have a savegame that consistenly throws OOM within a few seconds of loading it.

**Comment by paulwedeck** [comment]
sorry to hear that. From what I can see the [RAM limit](https://stackoverflow.com/questions/73262584/how-do-you-go-over-512mb-of-memory-in-an-android-app) in Android is hard coded.
I am not saying that in your specific case JSettlers isn't using some unreasonable amount of memory, but depending on the map this might just be a limitation of the platform and not of JSettlers.

**Comment by matusfaro** [comment]
Interesting, I didn't know this was a system limitation.
