### ISSUE TITLE
Cannot create new game.

### ISSUE THREAD

**Issue by christian179717** [paulwedeck/settlers-remake#79]
Hello,

I don't know why or if I does not know the right way to do it, but i cannot create a new game.

![grafik](https://github.com/paulwedeck/settlers-remake/assets/89655752/1042fa8c-27ca-40b5-9510-64b45365c80d)

If I click on "Einzelspiel starten" nothing happens.

**Comment by christian179717** [comment]
![grafik](https://github.com/paulwedeck/settlers-remake/assets/89655752/c8a7301f-6401-464c-8bd4-e05d90179d46)

In maps folder.

**Comment by christian179717** [comment]
0.6.0.7 did not work too.

**Comment by paulwedeck** [comment]
hmm, please run the jar file from the command line and send me the output. Maybe there is an error or something.
My other guess is that your S3 folder is not actually valid but I don't know why this would break the map list

**Comment by christian179717** [comment]
If I run JSettlers in Terminal the maps are shown:
![grafik](https://github.com/paulwedeck/settlers-remake/assets/89655752/8f76be41-d169-4184-8268-f7a21554782c)

But there are warnings:
```
$ java -jar JSettlers.jar
Source: (file:/home/user/JSettlers/JSettlers.jar <no signer certificates>)
Warning: Could not load LocaleSuffix [locale=de_DE, useCountry=true]. Falling back to next file.
[LWJGL] Failed to load a library. Possible solutions:
	a) Install the library or the driver that provides the library.
	b) Ensure that the library is accessible from the system library paths.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
```

**Comment by paulwedeck** [comment]
great!
These errors are completely expected
I don't know how exactly you previously started JSettlers but I guess you had a wrong working directory.
You could try creating a link file with the correct working directory to fix this (if you have an issue with starting it from the cmd every time).
