### ISSUE TITLE
Android Release 6.0.8 APK installing as version 6.0.7-alpha2

### ISSUE THREAD

**Issue by BRBsoup** [paulwedeck/settlers-remake#80]

**Comment by paulwedeck** [comment]
Where does it say 6.0.7-alpha2?
It is certainly not good if I messed up the versioning scheme somewhere but, in my opinion, this is literally not an issue.
Therefore, I will close this one.

**Comment by BRBsoup** [comment]
> Where does it say 6.0.7-alpha2?
> It is certainly not good if I messed up the versioning scheme somewhere but, in my opinion, this is literally not an issue.
> Therefore, I will close this one.

Android App Info for the app after installing

**Comment by BRBsoup** [comment]
> Where does it say 6.0.7-alpha2?
> It is certainly not good if I messed up the versioning scheme somewhere but, in my opinion, this is literally not an issue.
> Therefore, I will close this one.

![Screenshot_20240103_082455_Package Manager.jpg](https://github.com/paulwedeck/settlers-remake/assets/120071873/8d50cc26-239e-4433-a097-842d4d0cf136)

![Screenshot_20240103_082942_Settings.jpg](https://github.com/paulwedeck/settlers-remake/assets/120071873/47f1eab9-dee7-49bc-b912-8d544e6edcba)

![Screenshot_20240103_082422_Package Manager.jpg](https://github.com/paulwedeck/settlers-remake/assets/120071873/4e16e32d-deb3-41f8-913d-eb6938bc0e62)

![Screenshot_20240103_082407_My Files.jpg](https://github.com/paulwedeck/settlers-remake/assets/120071873/1015a38e-5719-4bfe-88cc-1faad41f2d8c)


The release and the apk provided as that release are different/mismatched...

**Comment by BRBsoup** [comment]
> Where does it say 6.0.7-alpha2? It is certainly not good if I messed up the versioning scheme somewhere but, in my opinion, this is literally not an issue. Therefore, I will close this one.

Regrettably, the versioning mismatch remains on the newest release :/
