### ISSUE TITLE
reuse original maps?

### ISSUE THREAD

**Issue by DJCrashdummy** [paulwedeck/settlers-remake#82]
as there are not that much maps built in JSettlers, is there a way to use or somehow utilize the original maps from the `Map` folder?

**Comment by paulwedeck** [comment]
Hi,
if I remember correctly, you just have to rename it to "maps".

**Comment by DJCrashdummy** [comment]
as it is nowhere even mentioned, i haven't thought that it would be that easy. :facepalm:
it's sufficient to do the same as with the other 2 folders... just dropping it as it is in the folder JSettlers has access to and you're ready to go.
*only when you try to play the one "TUTORIAL" map (`T1.MAP`) JSettlers crashes (and also its preview isn't shown), but i guess this is because special tutorial case.*

i added the `Map` folder as optional to the readme: #84.
