### ISSUE TITLE
Versioning mismatch on the latest release

### ISSUE THREAD

**Issue by BRBsoup** [paulwedeck/settlers-remake#83]
> Where does it say 6.0.7-alpha2?
> It is certainly not good if I messed up the versioning scheme somewhere but, in my opinion, this is literally not an issue.
> Therefore, I will close this one.

@paulwedeck 

![Screenshot_20240103_082455_Package Manager.jpg](https://github.com/paulwedeck/settlers-remake/assets/120071873/8d50cc26-239e-4433-a097-842d4d0cf136)

![Screenshot_20240103_082942_Settings.jpg](https://github.com/paulwedeck/settlers-remake/assets/120071873/47f1eab9-dee7-49bc-b912-8d544e6edcba)

![Screenshot_20240103_082422_Package Manager.jpg](https://github.com/paulwedeck/settlers-remake/assets/120071873/4e16e32d-deb3-41f8-913d-eb6938bc0e62)

![Screenshot_20240103_082407_My Files.jpg](https://github.com/paulwedeck/settlers-remake/assets/120071873/1015a38e-5719-4bfe-88cc-1faad41f2d8c)

The release and the apk provided as that release are different/mismatched...

_Originally posted by @BRBsoup in https://github.com/paulwedeck/settlers-remake/issues/80#issuecomment-1874955954_

**Comment by paulwedeck** [comment]
This should be fixed now. If not, please reopen the issue.
